<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="thingML" nsURI="xthingml" nsPrefix="thingML">
  <eClassifiers xsi:type="ecore:EClass" name="DynamicInstance">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicProperties" upperBound="-1" eType="//DynamicProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicCompositeStates" upperBound="-1" eType="//DynamicCompositeState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionFrame" lowerBound="1" eType="//Frame" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../../plugin/thingml/model/generated/ThingML.ecore#//Instance"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeFrame" lowerBound="1" eType="//Frame"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicPorts" upperBound="-1" eType="//DynamicPort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicProperty" eSuperTypes="//ValueContainer">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../../plugin/thingml/model/generated/ThingML.ecore#//Property"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true">
    <eAnnotations source="aspect"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullValue" eSuperTypes="//Value">
    <eAnnotations source="aspect"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerValue" eSuperTypes="//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayValue" eSuperTypes="//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" unique="false" upperBound="-1" eType="//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProxyValue" eSuperTypes="//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../../plugin/thingml/model/generated/ThingML.ecore#//Expression"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayProxyValue" eSuperTypes="//ProxyValue">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayProxyEntries" upperBound="-1" eType="//ArrayProxyEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayProxyEntry">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexExpression" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../../plugin/thingml/model/generated/ThingML.ecore#//Expression"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicCompositeState">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeState" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../../plugin/thingml/model/generated/ThingML.ecore#//CompositeState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../../plugin/thingml/model/generated/ThingML.ecore#//State"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Frame">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childFrame" eType="//Frame" containment="true" eOpposite="//Frame/parentFrame"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentFrame" eType="//Frame" eOpposite="//Frame/childFrame"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootContext" lowerBound="1" eType="//Context" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topContext" lowerBound="1" eType="//Context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" eType="//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childContext" eType="//Context" containment="true" eOpposite="//Context/parentContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentContext" eType="//Context" eOpposite="//Context/childContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicVariables" upperBound="-1" eType="//DynamicVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicVariable" eSuperTypes="//ValueContainer">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../../plugin/thingml/model/generated/ThingML.ecore#//Variable"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="//Value">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicPort">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../../plugin/thingml/model/generated/ThingML.ecore#//Port"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivedMessages" upperBound="-1" eType="//DynamicMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedPorts" upperBound="-1" eType="//DynamicPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicMessage">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../../plugin/thingml/model/generated/ThingML.ecore#//Message"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="//Value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueContainer" abstract="true">
    <eAnnotations source="aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="//Value"/>
  </eClassifiers>
</ecore:EPackage>
